services:
  - type: web
    name: shop-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn shop_backend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your_secret_key_here
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        value: your_database_url_here
